FYP App/Controllers/UserVerifyController.cs
using ClosedXML.Excel;
using FYP_App.Models;
using FYP_App.Services;
using PagedList;
using System;
using System.Data;
using System.IO;
using System.Linq;
using System.Web.Mvc;

namespace FYP_App.Controllers
{
    public class UserVerifyController : Controller
    {
        #region XL
        public ActionResult xl()
        {
            DbModels entities = new DbModels();
            DataTable dt = new DataTable("Grid");
            dt.Columns.AddRange(new DataColumn[6] { new DataColumn("ID"),
                                            new DataColumn("User Name"),
                                            new DataColumn("User Email"),
                                            new DataColumn("User Phone") ,
                                            new DataColumn("User Password") ,
                                            new DataColumn("User Account status") });

            var users = from user in entities.Sign_Up
                            select user;

            foreach (var user in users)
            {
                dt.Rows.Add(user.ID, user.Name, user.Email, user.Phone, user.Password,user.Status);
            }

            using (XLWorkbook wb = new XLWorkbook())
            {
                wb.Worksheets.Add(dt);
                using (MemoryStream stream = new MemoryStream())
                {
                    wb.SaveAs(stream);
                    return File(stream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "Users.xlsx");
                }
            }
        }
        #endregion 

        #region User_Index_By_Admin
        [HttpGet]
        public ActionResult Index(int? i)
        {
            using (DbModels db1 = new DbModels())
            {
                var drafts = db1.Sign_Up.ToList().ToPagedList(i ?? 1, 5);
                return View(drafts);
            }
        }
        #endregion

        #region Garbage_Code

        //// GET: UserVerify/Create
        //[HttpGet]
        //public ActionResult Create()
        //{
        //    return View();
        //}

        //// POST: UserVerify/Create
        //[HttpPost]
        //public ActionResult Create(Sign_Up sign)
        //{
        //    // TODO: Add insert logic here
        //    using (DbModels db = new DbModels())
        //    {
        //        db.Sign_Up.Add(sign);
        //        db.SaveChanges();
        //    }
        //    return RedirectToAction("Index");
        //}

        //// GET: UserVerify/Edit/5
        //public ActionResult Edit(int id)
        //{
        //    using (DbModels db = new DbModels())
        //    {
        //        return View(db.Sign_Up.Where(x => x.ID == id).FirstOrDefault());

        //    }
        //}

        //// POST: UserVerify/Edit/5
        //[HttpPost]
        //public ActionResult Edit(int id, Sign_Up sign)
        //{
        //    try
        //    {
        //        using (DbModels db = new DbModels())
        //        {
        //            db.Entry(sign).State = EntityState.Modified;

        //            db.SaveChanges();

        //        }
        //        return RedirectToAction("Index");
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}
        #endregion

        #region User_Delete_by_Admin
        [HttpGet]
        public ActionResult Delete(int id, Sign_Up sign)
        {
            using (DbModels db = new DbModels())
            {
                sign = db.Sign_Up.Where(x => x.ID == id).FirstOrDefault();
                db.Sign_Up.Remove(sign);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
        }
        #endregion

        #region User_Create_By_Admin
        [HttpGet]
        public PartialViewResult Creates()
        {
            return PartialView("Creates", new Models.Sign_Up());
        }
        [HttpPost]
        public JsonResult Creates(Sign_Up sign_Up)
        {
            if (ModelState.IsValid)
            {
                DbModels sd = new DbModels();
                sd.Sign_Up.Add(sign_Up);
                sd.SaveChanges();
                return Json("Account Created Successfully !!", JsonRequestBehavior.AllowGet);
            }
            else
            {




                return Json("Invalid Entry, Please Check your entries");
            }

        }
        #endregion

        #region User_Edit_By_Admin
        [HttpGet]
        public PartialViewResult Editt(Int32 ID)
        {
            DbModels sd = new DbModels();
            Sign_Up emp = sd.Sign_Up.Where(x => x.ID == ID).FirstOrDefault();
            Crudclass empclass = new Crudclass();
            empclass.Name = emp.Name;
            empclass.Password = emp.Password;
            empclass.Phone = emp.Phone;
            empclass.Status = emp.Status;
            empclass.Email = emp.Email;
            return PartialView(empclass);
        }
        [HttpPost]
        public JsonResult Editt(Sign_Up emp)
        {
            if (ModelState.IsValid)
            {

                DbModels sd = new DbModels();
                int empp = emp.ID;
                Sign_Up emptb = sd.Sign_Up.Where(x => x.ID == empp).FirstOrDefault();
                Crudclass empclass = new Crudclass();
                emptb.Name = emp.Name;
                emptb.Password = emp.Password;
                emptb.Phone = emp.Phone;
                emptb.Status = emp.Status;
                emptb.Email = emp.Email;
                sd.SaveChanges();
                Email_Sender email_Sender = new Email_Sender();
                email_Sender.Profile_Update(emptb.Email);
                return Json("Account Updated Successfully !!", JsonRequestBehavior.AllowGet);

            }
            else
            {






                return Json("Invalid Entry, Please Check your entries");
            }
        }
            #endregion


        

        }
}


    

FYP App/Views/UserVerify/Create.cshtml
@model FYP_App.Models.Sign_Up

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/AdminLayOut.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Sign_Up</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Status, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

FYP App/Views/UserVerify/Creates.cshtml
@model FYP_App.Models.Sign_Up
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
<script src="~/Scripts/jquery-1.9.1.js"></script>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.2.0/js/bootstrap.min.js"></script>
<div @*style="background-color:#E6E6FA"*@>
   
    <form>

        <div class="form-group">
            <label class=" font-weight-bold">User's Name</label>

            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @placeholder = "Full Name*", required = "required", type = "text" } })
            @Html.ValidationMessageFor(model => model.Name)
            <p style="color:cornflowerblue"><small>Name Should be in Format</small></p>

        </div>
        <div class="form-group">
            <label class=" font-weight-bold">User's Email</label>
            @Html.TextBoxFor(model => model.Email, new { @class = "form-control", @placeholder = "Email Address*", required = "required", type = "Email" })
            <p style="color:cornflowerblue"><small>Email Should be in Format</small></p>

        </div>
        <div class="form-group">
            <label class=" font-weight-bold">User's Phone Number</label>
            @Html.TextBoxFor(model => model.Phone, new { @class = "form-control", @placeholder = "Phone Number ", required = "required", type = "Number" })
            <p style="color:cornflowerblue"><small>Phone Should be in Format</small></p>

        </div>
        <div class="form-group">
            <label class=" font-weight-bold">Account Password</label>
            @Html.TextBoxFor(model => model.Password, new { @class = "form-control", @placeholder = "Account Password *", required = "required", type = "Password" })

        </div>
        <div class="form-group">
            <label class=" font-weight-bold">Account Status	</label>


            @Html.DropDownListFor(model => model.Status, new List<SelectListItem>
                               {

                                   new SelectListItem{Text="Approved", Value="Approved"},
                                   new SelectListItem{Text="Dis-Approved", Value="Dis-Approved"} },
                                   "Update Account Status ",
                                   new { @class = "form-control" })

        </div>
        <p>
            <div class="col-md-offset-2 col-md-10">

                <button type="submit" style="margin-bottom:10px" onclick="savedetails()" class="btn btn-success btn-sm btn-lg " >Submit</button>

                @* <input value="Create" class="btn btn-success" style="margin-bottom:10px" onclick="savedetails()" />*@
                <input type="reset" value="Reset" class="btn btn-danger" style="margin-bottom:10px" />


            </div>

        </p>

    </form>




</div>
<script type="text/javascript">

    function savedetails() {
        var ID = $("#ID").val();
        var Name = $("#Name").val();
        var Email = $("#Email").val();
        var Phone = $("#Phone").val();
        var Password = $("#Password").val();
        var Status = $("#Status").val();
        var insertem = { "ID": ID, "Name": Name, "Email": Email, "Phone": Phone, "Password": Password, "Status": Status };

        $.post('/UserVerify/Creates', insertem,
            function (data = insertem) {
                debugger
                console.log(data)
                alert(data);
                if (data.post == true) { location = location.href; } else {
                  
                }}
          
            , 'json');

        confirm("Are You Sure to Submit This ?");
        //function (data) {
        //    if (data.post == true) { location = location.href; }

        //}, 'json');

    }
        debugger
        //if (confirm("Are You Sure to Add This ?") == true) {

        //    $.post('/UserVerify/Creates', insertem,
        //        function (data) { if (data) { location = location.href; } },
        //        success = console.log("saved")
        //        , 'json')
        //        .fail(function () {
        //            alert("Invalid Entry, Please Check your entries");
        //        })
        //}
        //else {
        //    return false;
        //}



    

</script>
<script src="custom.js"></script>
<script>
    $('.loading').on('click', function () {
        var $btn = $(this);
        $btn.button('loading');
        setTimeout(function () {
            $btn.button('reset');
        }, 4000);
    });

</script>

FYP App/Views/UserVerify/Edit.cshtml
@model FYP_App.Models.Sign_Up

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/AdminLayOut.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Sign_Up</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Status, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

FYP App/Views/UserVerify/Editt.cshtml
@model FYP_App.Models.Crudclass


<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
<script src="~/Scripts/jquery-1.9.1.js"></script>
@*@Html.HiddenFor(model => model.emid)*@
<br />

<div class="form-group">
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <label class=" font-weight-bold">User's Name</label><br />
    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
    @Html.ValidationMessageFor(model => model.Name)
</div>
<div class="form-group">
    <label class=" font-weight-bold">User's Email</label>
    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })

</div>
<div class="form-group">
    <label class=" font-weight-bold">User's Phone Number</label>
    @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
</div>

<div class="form-group">
    <label class=" font-weight-bold">Account Password</label>
    @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })

</div>

<div class="form-group">
    <label class=" font-weight-bold">Account Status	</label>


    @Html.DropDownListFor(model => model.Status, new List<SelectListItem>
                       {

                           new SelectListItem{Text="Approved", Value="Approved"},
                           new SelectListItem{Text="Dis-Approved", Value="Dis-Approved"} },
                           "Update Account Status ",
                           new { @class = "form-control" })

</div>
<p>
    <div class="col-md-offset-2 col-md-10">
        <input type="submit" value="Update" class="btn btn-success" style="margin-bottom:10px" onclick="savedetails()" />
    </div>

</p>

<div hidden>
    id:@Html.EditorFor(model => model.ID)
    <br />

    @*name:@Html.EditorFor(model => model.Name)*@

    <br />
    phone:@Html.EditorFor(model => model.Phone)
    <br />
    password:@Html.EditorFor(model => model.Password)
    <br />
    Status:@Html.EditorFor(model => model.Status)
    <br />
    Status:@Html.EditorFor(model => model.Email)
    <p>
        <input type="button" value="Update" onclick="savedetails()" />

    </p>
</div>
<script type="text/javascript">
    function savedetails() {

        var ID = $("#ID").val();
        var Name = $("#Name").val();
        var Email = $("#Email").val();
        var Password = $("#Password").val();
        var Phone = $("#Phone").val();
        var Status = $("#Status").val();
        var insertem = { "ID": ID, "Name": Name, "Password": Password, "Phone": Phone, "Status": Status, "Email": Email };
        if (confirm("Are You Sure to Update This ?") == true) {
            debugger
            $.post('/UserVerify/Editt', insertem,
                function (data = insertem) {
                    console.log(data)
                    alert(data);
                    if (data) { location = location.href; }
                },
                success = console.log("s")
                , 'json')
                .fail(function () {
                    alert("Invalid Entry, Please Check your entries");
                })
        }
        else {
            return false;
        }



    }
    /* $.ajax({*/

    //    type: "POST",
    //    url: "/Test/Index",
    //    data: myformdata,
    //    success: function () {
    //        $("#loaderDiv").hide();
    //        $("#myModal").modal("hide");

    //    }

    //})

</script>
@*<script type="text/javascript">
    function savedetails() {

        var ID = $("#ID").val();
        var Name = $("#Name").val();
        var Password = $("#Password").val();
        var Phone = $("#Phone").val();
        var Status = $("#Status").val();
        var Email = $("#Email").val();

        var insertem = { "ID": ID, "Name": Name, "Password": Password, "Phone": Phone, "Status": Status, "Email": Email };
        if (confirm("Are You Sure to Update This ?") == true) {
            debugger
            $.post('/UserVerify/Editt', insertem,
                function (data) { if (data) { location = location.href; } },
                success = console.log("s")
                , 'json')
                .fail(function () {
                    alert("Invalid Entry, Please Check your entries");
                })
        }
        else {
            return false;
        }



    }

    //    $.post('/UserVerify/Editt', insertem,
    //        function (data) { if (data) { location = location.href; } }, 'json');

    //    confirm("Are You Sure to Update This ?");
    //} $.ajax({

    //    type: "POST",
    //    url: "/Test/Index",
    //    data: myformdata,
    //    success: function () {
    //        $("#loaderDiv").hide();
    //        $("#myModal").modal("hide");

    //    }

    //})

</script>*@

FYP App/Views/UserVerify/Index.cshtml
@model IPagedList<FYP_App.Models.Sign_Up>
@using PagedList.Mvc;
@using PagedList;

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/AdminLayOut.cshtml";
}
<html>
<head>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>


    <link href="https://unpkg.com/bootstrap-table@1.18.1/dist/bootstrap-table.min.css" rel="stylesheet">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

    <script src="https://unpkg.com/bootstrap-table@1.18.1/dist/bootstrap-table.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

    @*<script src="~/Content/sweetalert/sweetalert2.min.js"></script>
    <script src="~/Content/sweetalert/sweetalert2.js"></script>
    <script src="~/Content/sweetalert/sweetalert2.all.min.js"></script>
    <script src="~/Content/sweetalert/sweetalert2.all.js"></script>
    <link href="~/Content/sweetalert/sweetalert2.min.css" rel="stylesheet" />
    <link href="~/Content/sweetalert/sweetalert2.css" rel="stylesheet" />*@
    <style>
        .pagination {
            background-color: #EDEDED;
            color: black;
            float: left;
            text-decoration: none;
        }

            .pagination a {
                color: black;
                float: left;
                padding: 8px 16px;
                text-decoration: none;
            }
    </style>

</head>

<body>
    <br />

    
    <button type="button" style="float:right"   onclick="location.href='@Url.Action("xl", "UserVerify")'" class="btn btn-success"  />   <img src="https://img.icons8.com/ios-filled/26/26e07f/ms-excel.png" /> &nbsp;&nbsp;<b>DOWNLOAD</b></button>
    <div id="openpopup" style="display:none"></div>
    <button id="btnAdd" onclick="createpopup();" class="btn btn-success" style="margin-bottom:10px"><i class="fa fa-plus"></i>Add New </button>
    <input class="form-control" id="myInput" type="text" placeholder="Search..">
    <table class="table table-success table-striped">
        <thread>
            <tr>

                <th>

                    ID

                </th>
                <th>
                    Name
                </th>
                <th>
                    Email
                </th>
                <th>
                    Phone #
                </th>
                <th>
                    Password
                </th>
                <th> Account Status</th>
                <th>Operations</th>
            </tr>
        </thread>


        @foreach (var item in Model)
        {
            <tbody id="myTable">
                <tr>
                    <td >
                        
                            @Html.DisplayFor(modelItem => item.ID)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Email)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Phone)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Password)
                    </td>
                    <td>

                        @if (item.Status == "Approved")
                        {
                            <h4>
                                <span class="badge bg-success">
                                    @Html.DisplayFor(modelItem => item.Status)
                                </span>
                            </h4>

                        }
                        else
                        {
                            <h5>
                                <span class="badge bg-danger">
                                    @Html.DisplayFor(modelItem => item.Status)
                                </span>
                            </h5>

                        }



                    </td>
                        @*<td>
                @Html.Raw("<input type='button'value=Edit  onclick='edit(" + item.ID + ")';>")
            </td>*@
                        <td>


                            @*  @Html.Raw("<input type='button'value= 'Update Profile' class='btn btn-success' onclick ='update(" + item.ID + ")';>")*@
                            <img src="https://img.icons8.com/android/24/000000/edit.png"
                                 @Html.Raw("<input type='button'value=Edit class='btn btn-mini btn-info icon-edit bigger-10'  onclick='edit(" + item.ID + ")'; >")

                    <!--<a onclick='edit(" + item.ID + ")'--> @*href="@Url.Action("Edit", "UserVerify", new { id = item.ID })"*@ <!--class="btn btn-mini btn-info icon-edit bigger-10"><img src="https://img.icons8.com/android/24/000000/edit.png" /></a>-->
                    <a onclick="return confirm('Are you sure you to delete this Record?');" href="@Url.Action("Delete", "UserVerify", new { id = item.ID })" class="btn btn-mini btn-info icon-edit bigger-10"><img src="https://img.icons8.com/ios-filled/24/000000/delete-forever.png" /></a>


                </td>
                </tr>
        </tbody>
    }


    </table>
    @Html.PagedListPager(Model, i => Url.Action("Index", "UserVerify", new { i }))


    <link href="https://cdn.datatables.net/1.10.15/css/dataTables.bootstrap.min.css" rel="stylesheet" />
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />
    <script>

        function showpopup() {
            Swal.fire(
                'Have Not Account?',
                'Make Your Account Through SignUp',
                'question'
            )
        }
        function dellpopups() {

        }
        function dellpopup() {
            Swal.fire({
                title: "Delete Successully !!",
                text: "",
                icon: "success",

                dangerMode: true,
            })

        }
        $(document).ready(function () {
            $("#myInput").on("keyup", function () {
                $(this).fadeIn();
                var value = $(this).val().toLowerCase();
                $("#myTable tr").filter(function () {
                    $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                });
            });
        });


        function createpopup() {
            var x = $("#openpopup");
            x.load('/UserVerify/Creates', function () {
                x.dialog({
                    show:
                        { effect: "slideToggle", duration: 500 },
                    hide:
                        { effect: "slideToggle", duration: 500 },

                    modal: true,
                    width: 650,
                    height: 670,
                    title: "Create User's Account",
                    resizeable: false

                });

            });



        }

        function edit(ID) {
            var x = $("#openpopup");
            x.load("/UserVerify/Editt?ID=" + ID, function () {
                x.dialog({
                    show:
                        { effect: "slideToggle", duration: 500 },
                    hide:
                        { effect: "slideToggle", duration: 500 },

                    modal: true,
                    width: 650,
                    height: 630,
                    title: "Update User's Account",
                    resizeable: false

                });
            });
        }





    </script>
</body>
</html>