FYP App/Models/Login.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace FYP_App.Models
{
    public class Login
    {
        public string Name { get; set; }
        public string Password { get; set; }
        public string Status { get; set; }
        public string LoginErrorMessage { get; set; }
    }
   
}

FYP App/Models/Sensor.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace FYP_App.Models
{
    public class Sensor
    {
        //public string ID { get; set; }
        public int Humidity {get; set; }
        public string Smoke { get; set; }
        public string Temperature { get; set; }
        public string Light { get; set; }
        public string Motion { get; set; }
        public string MoistureAvailable { get; set; }
        public string HumidityOutput { get; set; }
        public string LightOUTPUT { get; set; }
        public string SmokeOUTPUT { get; set; }
        public string TempOutput { get; set; }
        public string MoisOUTPUT { get; set; }
        public string MotionOutput { get; set; }
        public string WaterAvailable { get; set; }

        public string WaterOUTPUT { get; set; }
        public string Body_Detected { get; set; }
        public string Door { get; set; }



    }
}

FYP App/Controllers/LoginController.cs
using FYP_App.Models;
using FYP_App.Services;
using System;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace FYP_App.Controllers
{
    public class LoginController : Controller
    {

       
        #region Database Objects

        SqlConnection con = new SqlConnection();
        SqlCommand com = new SqlCommand();
        SqlDataReader dr;
        DbModel1s db1 = new DbModel1s();
        DbModels db2 = new DbModels();
        #endregion

        #region UserDashBoard
        public ActionResult Count()
        {
            connectionstring();
            ViewBag.Countapproveduser = db2.Sign_Up.Count(a => a.Status == "Approved");
            ViewBag.Countuser = db2.Sign_Up.Count();
            ViewBag.Counttotal = db1.Complaint_DB.Count();
            ViewBag.Count = db1.Complaint_DB.Count(a => a.Status == "Solved");
            return View();
        }
        #endregion

        #region Connectionstring
        void connectionstring()
        {
            con.ConnectionString = "Data Source=DESKTOP-BSAK185; Initial Catalog =FYP database; Integrated Security = True";
        }
        #endregion

        #region Login
     
        [HttpGet]
        public ActionResult Login()
        {
            FormsAuthentication.SignOut();
            Session.Abandon();
            return View();
        }
        [HttpPost]
        public ActionResult Verify(Login login)
        {
           
            Count();
            Session["Name"] = login.Name;
            connectionstring();
            con.Open();
            com.Connection = con;
            com.CommandText = "select * from Sign_Up where Email='" + login.Name + "' and Password='" + login.Password + "' and Status='Approved'  ";
            dr = com.ExecuteReader();
            if (dr.Read() == true)
            {

                con.Close();
                con.Open();
                SqlCommand cmd = new SqlCommand("select Status from Sign_Up where Email='" + login.Name + "'", con);
                SqlCommand cmds = new SqlCommand("select COUNT(*) from Complaint_DB where User_Email= '" + login.Name +"'", con);
                SqlCommand cmdss = new SqlCommand("select COUNT(*) from Complaint_DB where User_Email='" + Session["Name"] + "' AND  Status = 'Solved'", con);

                var result = (string)cmd.ExecuteScalar();
                var result2 = (int)cmds.ExecuteScalar();
                var result3 = (int)cmdss.ExecuteScalar();
                ViewBag.Account_Status = result;
                ViewBag.Total_Complaint_Status = result2;
                ViewBag.Solved_Complaint_Status = result3;
                //con.Close();
                return RedirectToAction("User_Dashborad");
            }

            else if (login.Name == "autoislamabad@gmail.com" && login.Password == "olx")
            {
                return RedirectToAction("Admin_Dashboard", "Sensor", null);

               // return RedirectToAction("Admin");

              //  return View("Admin");
            }
            else
            {
                ViewBag.error = "Invalid Username or Password";
            }
            return View("Login");


        }
        #endregion

        #region ForgotPassword
        [HttpGet]
        [OutputCache(Duration = 500)]
        public ActionResult ForgotPassword()
        {
            return View();
        }
        [HttpPost]

        public ActionResult ForgotPassword(Login login)
        {
            
            String password;
            String mycon = "Data Source=DESKTOP-BSAK185; Initial Catalog =FYP database; Integrated Security = True";
            String myquery = "select * from Sign_Up where Email='" + login.Name + "' ";
            SqlConnection con = new SqlConnection(mycon);
            SqlCommand cmd = new SqlCommand();
            cmd.CommandText = myquery;
            cmd.Connection = con;
            SqlDataAdapter da = new SqlDataAdapter();
            da.SelectCommand = cmd;
            DataSet ds = new DataSet();
            da.Fill(ds);
            if (ds.Tables[0].Rows.Count > 0)
            {
                password = ds.Tables[0].Rows[0]["Password"].ToString();
                Email_Sender email_Sender = new Email_Sender();
                email_Sender.Password_Email(login.Name , password);
                
                ViewBag.SuccessMessage = "Check Your Email Inbox ✔️";
            }
            else
            {
                
                ViewBag.errors = "Invalid Email ❌";
            }

            return View("ForgotPassword");
        }
        #endregion

        #region Error_Action
        public ActionResult Error()
        {
            return View();
        }
        #endregion

        #region User_Dashborad
        public ActionResult User_Dashborad(Login login)
        {
            connectionstring();
            con.Open();
            SqlCommand cmd = new SqlCommand("select Status from Sign_Up where Email='" + Session["Name"] + "'", con);
            SqlCommand cmds = new SqlCommand("select COUNT(*) from Complaint_DB where User_Email= '" + Session["Name"] + "'", con);
            SqlCommand cmdss = new SqlCommand("select COUNT(*) from Complaint_DB where User_Email='" + Session["Name"] + "' AND  Status = 'Solved'", con);
            var result = (string)cmd.ExecuteScalar();
            var result2 = (int)cmds.ExecuteScalar();
            var result3 = (int)cmdss.ExecuteScalar();
            ViewBag.Account_Status = result;
            ViewBag.Total_Complaint_Status = result2;
            ViewBag.Solved_Complaint_Status = result3;
            
          
            return View();
        }
        #endregion

        public ActionResult Logout()

        {

            Response.Cache.SetCacheability(HttpCacheability.NoCache);
            Response.Cache.SetExpires(DateTime.UtcNow.AddHours(-1));
            Response.Cache.SetNoStore();
            FormsAuthentication.SignOut();
            Session.Abandon();
            return   RedirectToAction("Login");
        }

    }
}

FYP App/Controllers/SensorController.cs
using FireSharp.Config;
using FireSharp.Interfaces;
using FireSharp.Response;
using FYP_App.Models;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace FYP_App.Controllers
{
    public class SensorController : Controller
    {
        #region BasePath
        IFirebaseConfig config = new FirebaseConfig
        {
            AuthSecret = "TBBto0oXxnvec1ANLb6LCyCOCFRCTHiA2ic6zdat",
            BasePath = "https://fyp-firebase-67d9c-default-rtdb.firebaseio.com/"
        };
        IFirebaseClient client;
        #endregion

        #region Sensor_View
        public ActionResult Index()
        {
            client = new FireSharp.FirebaseClient(config);
            FirebaseResponse response = client.Get("Sensors");
            dynamic data = JsonConvert.DeserializeObject<dynamic>(response.Body);
            var list = new List<Sensor>();
            try
            {
                foreach (var item in data)
                {
                  
                    list.Add(JsonConvert.DeserializeObject<Sensor>(((JProperty)item).Value.ToString()));
                }
               
                

            }
            catch
            {
                ModelState.AddModelError(string.Empty, "No Data Here");
            }
            return View(list);
        }
        public ActionResult Admin_Dashboard()
        {
            DbModel1s db1 = new DbModel1s();
            DbModels db2 = new DbModels();
            ViewBag.Countapproveduser = db2.Sign_Up.Count(a => a.Status == "Approved");
            ViewBag.Countuser = db2.Sign_Up.Count();
            ViewBag.Counttotal = db1.Complaint_DB.Count();
            ViewBag.Count = db1.Complaint_DB.Count(a => a.Status == "Solved");
            client = new FireSharp.FirebaseClient(config);
            FirebaseResponse response = client.Get("Sensors");
            dynamic data = JsonConvert.DeserializeObject<dynamic>(response.Body);
            var list = new List<Sensor>();
            try
            {
                foreach (var item in data)
                {

                    list.Add(JsonConvert.DeserializeObject<Sensor>(((JProperty)item).Value.ToString()));
                }



            }
            catch
            {
                ModelState.AddModelError(string.Empty, "No Data Here");
            }
            return View(list);
        }
        #endregion
    }
}

FYP App/Controllers/SignUpController.cs
using FYP_App.Models;
using System.Data.SqlClient;
using System.Web.Mvc;

namespace FYP_App.Controllers
{
    public class SignUpController : Controller
    {

        #region Database_Objects
        readonly SqlConnection con = new SqlConnection();
        readonly SqlCommand com = new SqlCommand();
        SqlDataReader dr;
        #endregion

        #region Connectionstring
        void connectionstring()
        {
            con.ConnectionString = "Data Source=DESKTOP-BSAK185; Initial Catalog =FYP database; Integrated Security = True";
        }
        #endregion

        #region Create_Account
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Sign_Up sign_Up)
        {
            if (ModelState.IsValid)
            {
                connectionstring();
                using (DbModels dbModel = new DbModels())
                {
                    con.Open();
                    com.Connection = con;
                    com.CommandText = "Select * from  Sign_Up where Email='" + sign_Up.Email + "'";
                    dr = com.ExecuteReader();
                    if (dr.Read())
                    {
                        ViewBag.alreadyregistermail = "Ohh ! \r You Can't create Your Account with this Email ❌ . \r Try Another One !!";
                    }
                    else
                    {

                        dbModel.Sign_Up.Add(sign_Up);
                        dbModel.SaveChanges();
                       // Email_Sender email_Sender = new Email_Sender();
                       // email_Sender.SignUp_Email(sign_Up.Email);
                        ViewBag.SuccessMessage = "Account Successfully ✔️ Wait for approval  !!";
                        ModelState.Clear();
                    }
                }
            }
            else
            {
                return View();
            }
            return View();
        }
        #endregion
    }
}

FYP App/Views/Login/Admin.cshtml
@model IEnumerable<FYP_App.Models.Sensor>
@{
    ViewBag.Title = "Admin";
    Layout = "~/Views/AdminLayOut.cshtml";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <!-- This file has been downloaded from Bootsnipp.com. Enjoy! -->
    <title>Information Cards - Bootsnipp.com</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="http://maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet">
    <style type="text/css">
        .my-card {
            position: absolute;
            left: 40%;
            top: -20px;
            border-radius: 50%;
        }
    </style>
    <script src="http://code.jquery.com/jquery-1.11.1.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
</head>
<body>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css
">


    <br />
    <br />
    <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
        <symbol id="check-circle-fill" fill="currentColor" viewBox="0 0 16 16">
            <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z" />
        </symbol>
        <symbol id="info-fill" fill="currentColor" viewBox="0 0 16 16">
            <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z" />
        </symbol>
        <symbol id="exclamation-triangle-fill" fill="currentColor" viewBox="0 0 16 16">
            <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
        </symbol>
    </svg>
    <div class="alert alert-success d-flex align-items-center" role="alert">
        <svg class="bi flex-shrink-0 me-2" width="34" height="34" role="img" aria-label="Success:"><use xlink:href="#check-circle-fill" /></svg>
        <h4>
            &nbsp;&nbsp;&nbsp;&nbsp;𝐂𝐨𝐧𝐠𝐫𝐚𝐭𝐮𝐥𝐚𝐭𝐢𝐨𝐧𝐬 ,𝐋𝐨𝐠𝐈𝐧 𝐒𝐮𝐜𝐜𝐞𝐬𝐬𝐟𝐮𝐥𝐥𝐲 !!
        </h4>
    </div>



    <div class="jumbotron">
        <div class="row w-100">

            <div class="col-md-3">
                <div class="card border-info mx-sm-1 p-3">
                    <div class="card border-info shadow text-info p-3 my-card"><span class="fa fa-user" aria-hidden="true"></span></div>
                    <div class="text-info text-center mt-3"><h4>𝐓𝐨𝐭𝐚𝐥 𝐔𝐬𝐞𝐫𝐬</h4></div>
                    <div class="text-info text-center mt-2"><h1>  @ViewBag.Countuser </h1></div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="card border-success mx-sm-1 p-3">
                    <div class="card border-success shadow text-success p-3 my-card"><span class="fa fa-eye" aria-hidden="true"></span></div>
                    <div class="text-success text-center mt-3"><h5>𝐀𝐩𝐩𝐫𝐨𝐯𝐞𝐝 𝐔𝐬𝐞𝐫𝐬</h5></div>
                    <div class="text-success text-center mt-2"><h1>  @ViewBag.Countapproveduser </h1></div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="card border-info mx-sm-1 p-3">
                    <div class="card border-info shadow text-info p-3 my-card"><span class="fa fa-inbox" aria-hidden="true"></span></div>
                    <div class="text-info text-center mt-3"><h4>𝐓𝐨𝐭𝐚𝐥 𝐂𝐨𝐦𝐩𝐥𝐚𝐢𝐧𝐭𝐬</h4></div>
                    <div class="text-info text-center mt-2"><h1>  @ViewBag.Counttotal </h1></div>
                </div>
            </div>

            <div class="col-md-3">
                <div class="card border-success mx-sm-1 p-3">
                    <div class="card border-success shadow text-success p-3 my-card"><span class="fa fa-inbox" aria-hidden="true"></span></div>
                    <div class="text-success text-center mt-3"><h5>𝐒𝐨𝐥𝐯𝐞𝐝 𝐂𝐨𝐦𝐩𝐥𝐚𝐢𝐧𝐭𝐬</h5></div>
                    <div class="text-success text-center mt-2"><h1>  @ViewBag.Count </h1></div>
                </div>
            </div>

        </div>
    </div>



    <script type="text/javascript">

    </script>
</body>
</html>

FYP App/Views/Login/ForgotPassword.cshtml
@model FYP_App.Models.Login

<title>
    Smart Establishment
</title>


<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Reset Password</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="assets/css/style.css">
    <link href="~/Content/preloader.css" rel="stylesheet" />
    <link href="~/Content/Forgetpassword.css" rel="stylesheet" />
  
    <link rel="stylesheet" type="text/css" href="custom.css">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.1.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.2.0/js/bootstrap.min.js"></script>
</head>

<div class="loader">
        <img src="~/Content/200.gif"  alt="Loading..." />
    </div>
<div class="login-dark">
    <form action="ForgotPassword" method="post">

        <h2 class="sr-only">Login Form</h2>
        <h6>Forget Your Password ?</h6>


        <div class="illustration"><i class="icon ion-ios-locked-outline"></i></div>

        <h6>Enter Your Email Here !!</h6>
        <hr>
        <p style="color:darkseagreen; text-align: center" ><b>@ViewBag.SuccessMessage </b></p>
        <p id="example" style="  color: red; text-align: center">
            <strong> @ViewBag.errors </strong>
        </p>

        <div class="form-group"><input id="StudentName" class="form-control" type="email" name="Name" placeholder="Enter Your Email" required autofocus></div>
        <div class="form-group">
            <button  class="btn btn-primary btn-block btn-lg loading buttonload" id="load" data-loading-text="<i class='fa fa-circle-o-notch fa-spin'></i> Loading...">Submit</button>
           </div>
            @*<div class="form-group"><button class="btn btn-primary btn-block" >Submit</button></div>*@
            <a href="@Url.Action("Login", "login")" class="btn btn-primary btn-block">Back to Login</a>

            <p style="color:darkseagreen"><b>  @Html.DisplayFor(Model => Model.LoginErrorMessage)</b></p>






</form>


</div>
<script src="custom.js"></script>
<script>
    $('.loading').on('click', function () {
        var $btn = $(this);
        $btn.button('loading');
        setTimeout(function () {
            $btn.button('reset');
        }, 5000);
    });

</script>
<script>



    function showDiv() {
        document.getElementById('welcomeDiv').style.display = "block";
    }



    window.addEventListener("load", function () {
        const loader = document.querySelector(".loader");
        loader.className += " hidden"; // class "loader hidden"
    });
</script>

FYP App/Views/Login/Login.cshtml
<title>
    Smart Establishment
</title>


<style>
    .login-dark {
        width: 100%;
        height: 100%;
        margin: 0;
        padding: 0;
        background: #475d62 url(https://images.unsplash.com/photo-1590447158019-883d8d5f8bc7?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=889&q=80);
        background-size: cover;
        position: relative;
    }

        .login-dark form {
            max-width: 320px;
            width: 90%;
            background-color: #1e2833;
            padding: 40px;
            border-radius: 4px;
            transform: translate(-50%, -50%);
            position: absolute;
            top: 50%;
            left: 50%;
            color: #fff;
            box-shadow: 3px 3px 4px rgba(0,0,0,0.2);
        }

        .login-dark .illustration {
            text-align: center;
            padding: 15px 0 20px;
            font-size: 100px;
            color: #2980ef;
        }

        .login-dark form .form-control {
            background: none;
            border: none;
            border-bottom: 1px solid #434a52;
            border-radius: 0;
            box-shadow: none;
            outline: none;
            color: inherit;
        }

        .login-dark form .btn-primary {
            background: #214a80;
            border: none;
            border-radius: 4px;
            padding: 11px;
            box-shadow: none;
            margin-top: 26px;
            text-shadow: none;
            outline: none;
        }

            .login-dark form .btn-primary:hover, .login-dark form .btn-primary:active {
                background: #214a80;
                outline: none;
            }

        

            .login-dark form .forgot:hover, .login-dark form .forgot:active {
                opacity: 1;
                text-decoration: none;
            }

        .login-dark form .btn-primary:active {
            transform: translateY(1px);
        }

    h6 {
        text-align: center;
    }
    body {
        font-family: "Open Sans", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", Helvetica, Arial, sans-serif;
    }
    
</style>



<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="assets/css/style.css">


    <script src="~/Content/sweetalert/sweetalert2.min.js"></script>
    <script src="~/Content/sweetalert/sweetalert2.js"></script>
    <script src="~/Content/sweetalert/sweetalert2.all.min.js"></script>
    <script src="~/Content/sweetalert/sweetalert2.all.js"></script>
    <link href="~/Content/sweetalert/sweetalert2.min.css" rel="stylesheet" />
    <link href="~/Content/sweetalert/sweetalert2.css" rel="stylesheet" />
    <link href="~/Content/backgraound.css" rel="stylesheet" />
</head>

<body>

    <div class="login-dark">
        <form action="Verify" method="post">
            @Html.AntiForgeryToken()

            <h2 class="sr-only">Login Form</h2>
            <h6 >Welcome Please Login</h6>

            <div class="illustration"><i class="icon ion-ios-locked-outline"></i></div>
            <p style="color:red;">
                <strong> @ViewBag.error </strong>
            </p>


            <p class="danger" role="alert">

            </p>
            <div class="form-group"><input id="StudentName" class="form-control" type="email" name="Name" placeholder="Enter Your Email" required autofocus></div>
            <div class="form-group"><input class="form-control" type="password" name="Password" placeholder="Enter Your Password" required id="myInput"></div>
            <input type="checkbox" onclick="myFunction()"> Show Password

            <div class="form-group"><button class="btn btn-primary btn-block" type="submit"   > LOGIN</button></div>



            <a href="@Url.Action("ForgotPassword", "Login")" class="forgot">
                <p style="text-align:center">Forget Password?</p>
            </a>
            <p style="text-align:center"><b>OR</b></p>

            <a href="#" onclick="showpopup()" class="forgot">
                <p style="text-align:center">Have'nt Any Account ?</p>
            </a>
            <a href="@Url.Action("Create", "SignUp")" class="btn btn-primary btn-block">Sign Up</a>
        </form>
    </div>
    <script>

        function showpopup() {
            Swal.fire(
                'Have Not Account?',
                'Make Your Account Through SignUp',
                'question'
            )
        }
        function myFunction() {
            var x = document.getElementById("myInput");
            if (x.type === "password") {
                x.type = "text";
            } else {
                x.type = "password";
            }
        }

           
    </script>
</body>