FYP App/Controllers/ComplaintController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using FYP_App.Models;
using System.Data.SqlClient;
using System.Data.Entity;
using System.Web.UI.WebControls;
using PagedList;
using System.Net.Mail;
using System.Net;
using FYP_App.Services;
using System.Data;
using System.Data.Entity.Infrastructure;
using ClosedXML.Excel;
using System.IO;

namespace FYP_App.Controllers
{
    public class ComplaintController : Controller
    {
        #region Database_Objcts
        readonly SqlConnection con = new SqlConnection();
        readonly SqlCommand com = new SqlCommand();
        SqlDataReader dr;
        #endregion

        #region Connectionstring
        void Connectionstring()
        {
            con.ConnectionString = "Data Source=DESKTOP-BSAK185; Initial Catalog =FYP database; Integrated Security = True";
        }
        #endregion

        #region Complaint_Edit_By_Admin
        [HttpGet]
        public ActionResult Edit(int id)
        {
            using (DbModel1s db = new DbModel1s())
            {
                return View(db.Complaint_DB.Where(x => x.Complaint_ID == id).FirstOrDefault());
            }
        }

        [HttpPost]
        public ActionResult Edit(Complaint_DB complaint)
        {
            try
            {
                using (DbModel1s db = new DbModel1s())
                {
                    db.Entry(complaint).State = EntityState.Modified;
                    db.SaveChanges();
                    Email_Sender email_Sender = new Email_Sender();
                    email_Sender.Complaint_Email(complaint.User_Email, complaint.Complaint_ID, complaint.Status);               
                }
                return RedirectToAction("Admin_Index");

            }

            catch
            {
                return RedirectToAction("Admin_Index");

              
            }
           // return vi("Admin_Index");
        }

        #endregion

        #region Admin_Delete
        [HttpGet]
        public ActionResult Admin_Delete(int id, Complaint_DB complaint_DB)
        {
            using (DbModel1s db = new DbModel1s())
            {
                complaint_DB = db.Complaint_DB.Where(x => x.Complaint_ID == id).FirstOrDefault();
                db.Complaint_DB.Remove(complaint_DB);
                db.SaveChanges();
                return RedirectToAction("Admin_Index");
            }
        }
        #endregion

        #region Complaint_Admin_Details
        [HttpGet]
        public ActionResult Admin_Details(int id)
        {
            using (DbModel1s db = new DbModel1s())
            {
                return View(db.Complaint_DB.Where(x => x.Complaint_ID == id).FirstOrDefault());
            }
        }
        #endregion

        #region Complaint_Admin_Index
        [HttpGet]
        public ActionResult Admin_Index(int? i)
        {
            try
            {
                using (DbModel1s db1 = new DbModel1s())
                {
                    var draftss = db1.Complaint_DB.ToList().OrderByDescending(d => d.Complaint_ID).ToPagedList(i ?? 1, 5);
                    return View(draftss);
                }
            }
            catch
            {
                return View("Login");
            }
        }
        #endregion

        #region Complaint_User_Index
        [HttpGet]
        public void RetrieveUserInfo(string Name)
        {
            try
            {
                Name = Session["Name"].ToString();
                using (DbModel1s db1 = new DbModel1s())
                {
                    Connectionstring();
                    con.Open();
                    com.Connection = con;
                    com.CommandText = "Select * from  Sign_Up where Email='" + Name + "'";
                    dr = com.ExecuteReader();
                    if (dr.Read())
                    {
                        DateTime now = DateTime.Now;
                        string id = dr.GetValue(0).ToString();
                        string name = dr.GetValue(1).ToString();
                        string email = dr.GetValue(2).ToString();
                        

                        ViewBag.Id = id;
                        ViewBag.name = name;
                        ViewBag.email = email;
                        ViewBag.date = now.ToString("MM/dd/yyyy hh:mm tt"); 
                    }
                }
            }
            catch
            {
                //session expire so we should go to logiin page again !!
                RedirectToAction("login");
            }
        }
        [HttpGet]
        public ActionResult Index(string Name, int? i)
        {
            try
            {
                using (DbModel1s db1 = new DbModel1s())
                {
                    if (Session["Name"] == null)
                    {
                        return RedirectToAction("LogIn", "Login");

                    }
                    else
                    {
                        Name = Session["Name"].ToString();
                        RetrieveUserInfo(Name);
                        var drafts = db1.Complaint_DB.Where(d => d.User_Email == Name).ToList().OrderByDescending(d => d.Complaint_ID).ToPagedList(i ?? 1, 5);
                        return View(drafts);
                    }
                }
            }
            catch
            {
                return RedirectToAction("LogIn", "Login"); 
            }
        }
        #endregion

        #region Complaint_Details_By_User
        [HttpGet]
        public ActionResult Details(int id)
        {
            using (DbModel1s db = new DbModel1s())
            {
                return View(db.Complaint_DB.Where(x => x.Complaint_ID == id).FirstOrDefault());

            }
        }
        #endregion

        #region Complaint_Create_By_user

        public ActionResult Create(string Name)
        {
            RetrieveUserInfo(Name);
            return View();
        }
        [HttpPost]
        public ActionResult Create(Complaint_DB complaint_DB, string Name)
        {
            try
            {
                using (DbModel1s db = new DbModel1s())
                {
                    RetrieveUserInfo(Name);
                    db.Complaint_DB.Add(complaint_DB);
                    db.SaveChanges();
                }

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        #endregion

        #region Complaint_delete_By_user
        [HttpGet]
        public ActionResult Delete(int id, Complaint_DB complaint_DB)
        {
            using (DbModel1s db = new DbModel1s())
            {
                complaint_DB = db.Complaint_DB.Where(x => x.Complaint_ID == id).FirstOrDefault();
                db.Complaint_DB.Remove(complaint_DB);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
        }
        #endregion

        #region Complaint_To_Excel
        public ActionResult xl()
        {
            DbModel1s entities = new DbModel1s();
            DataTable dt = new DataTable("Grid");
            dt.Columns.AddRange(new DataColumn[7] { new DataColumn("Complaint_ID"),
                                            new DataColumn("User_Email"),
                                            new DataColumn("User_Name"),
                                            new DataColumn("Date") ,
                                            new DataColumn("Subject") ,
                                            new DataColumn("Description"),
                                            new DataColumn("Complaint Status")
            });

            var complaint = from complaints in entities.Complaint_DB
                        select complaints;

            foreach (var complaints in complaint)
            {
                dt.Rows.Add(complaints.Complaint_ID, complaints.User_Email, complaints.User_Name, complaints.Date, complaints.Subject, complaints.Description, complaints.Status);
            }

            using (XLWorkbook wb = new XLWorkbook())
            {
                wb.Worksheets.Add(dt);
                using (MemoryStream stream = new MemoryStream())
                {
                    wb.SaveAs(stream);
                    return File(stream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "Complaint.xlsx");
                }
            }
        }
        #endregion


    }
}

FYP App/Views/Complaint/Admin_Details.cshtml
@model FYP_App.Models.Complaint_DB

@{
    ViewBag.Title = "Admin_Details";
    Layout = "~/Views/AdminLayOut.cshtml";
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
        * {
            box-sizing: border-box;
        }

        input[type=text], select, textarea {
            width: 100%;
            padding: 12px;
            border: 1px solid rgb(70, 68, 68);
            border-radius: 4px;
            resize: vertical;
        }

        input[type=email], select, textarea {
            width: 100%;
            padding: 12px;
            border: 1px solid rgb(70, 68, 68);
            border-radius: 4px;
            resize: vertical;
        }

        label {
            padding: 12px 12px 12px 0;
            display: inline-block;
        }

        input[type=submit] {
            background-color: rgb(37, 116, 161);
            color: white;
            padding: 12px 20px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            float: right;
        }

            input[type=submit]:hover {
                background-color: #45a049;
            }

        .container {
            border-radius: 5px;
            background-color: #f2f2f2;
            padding: 20px;
        }

        .col-25 {
            float: left;
            width: 25%;
            margin-top: 6px;
        }

        .col-75 {
            float: left;
            width: 75%;
            margin-top: 6px;
        }

        /* Clear floats after the columns */
        .row:after {
            content: "";
            display: table;
            clear: both;
        }

        /* Responsive layout - when the screen is less than 600px wide, make the two columns stack on top of each other instead of next to each other */
    </style>
</head>
<body>
    <br />
    <br />
    <br />
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
      
<div class="container">
    <h2>
        ℂ𝕠𝕞𝕡𝕝𝕒𝕚𝕟𝕥 #    @Html.DisplayFor(model => model.Complaint_ID)
        &nbsp;&nbsp;  &nbsp;&nbsp;   &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp;  &nbsp;&nbsp; &nbsp;&nbsp;  &nbsp;&nbsp;&nbsp;&nbsp;  &nbsp;&nbsp; 
        &nbsp;&nbsp;&nbsp;&nbsp; 𝕀𝕤𝕤𝕦𝕖 𝕕𝕒𝕥𝕖 :  @Html.DisplayFor(model => model.Date)
    </h2>

    <form>

        <div class="row">
            <div class="col-25">
                <label for="fname">User Name</label>
            </div>
            <div class="col-75">

                @Html.TextBoxFor(model => model.User_Name, new { @class = "form-control", @readonly = "readonly" })
            </div>
        </div>
        <div class="row">
            <div class="col-25">
                <label for="lname">User Email</label>
            </div>
            <div class="col-75">
                @Html.TextBoxFor(model => model.User_Email, new { @class = "form-control", @readonly = "readonly" })



            </div>
        </div>
        <div class="row">
            <div class="col-25">
                <label for="fname">Complaint Status</label>
            </div>
            <div class="col-75">

                @Html.TextBoxFor(model => model.Status, new { @class = "form-control", @readonly = "readonly" })
            </div>
        </div>
        <div class="row">
            <div class="col-25">
                <label for="email">Complaint Subject </label>
            </div>
            <div class="col-75">
                @Html.TextBoxFor(model => model.Subject, new { @class = "form-control", @readonly = "readonly" })
            </div>
        </div>

        <div class="row">
            <div class="col-25">
                <label for="feed_back">Complaint Description</label>
            </div>
            <div class="col-75">

                @Html.TextAreaFor(model => model.Description, new { @style = "height:200px", @readonly = "readonly" })
            </div>
        </div>


        <div>
            <div class="row">
                <a href="@Url.Action("Admin_Index","Complaint")" class="btn btn-mini btn-info icon-edit bigger-07"><img src="https://img.icons8.com/flat_round/30/000000/back--v1.png" />Back to List </a>

            </div>
        </div>

    </form>
</div>
    }
</body>

</html>

FYP App/Views/Complaint/Admin_Index.cshtml
@model IPagedList<FYP_App.Models.Complaint_DB>
@using PagedList.Mvc;
@using PagedList;
@{
    ViewBag.Title = "Admin_Index";
    Layout = "~/Views/AdminLayOut.cshtml";
}

<html>
<head>
    <link href="https://unpkg.com/bootstrap-table@1.18.1/dist/bootstrap-table.min.css" rel="stylesheet">

    <script src="https://unpkg.com/bootstrap-table@1.18.1/dist/bootstrap-table.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>



    @*<script src="~/Content/sweetalert/sweetalert2.min.js"></script>
        <script src="~/Content/sweetalert/sweetalert2.js"></script>
        <script src="~/Content/sweetalert/sweetalert2.all.min.js"></script>
        <script src="~/Content/sweetalert/sweetalert2.all.js"></script>
        <link href="~/Content/sweetalert/sweetalert2.min.css" rel="stylesheet" />
        <link href="~/Content/sweetalert/sweetalert2.css" rel="stylesheet" />*@

    <style>
        .pagination {
            background-color: #EDEDED;
            color: black;
            float: left;
            text-decoration: none;
        }

            .pagination a {
                color: black;
                float: left;
                padding: 8px 16px;
                text-decoration: none;
            }
    </style>
</head>
<body>
    <br />
    <br />
    <br />
    <button type="button" style="float:right" onclick="location.href='@Url.Action("xl", "Complaint")'" class="btn btn-success" />   <img src="https://img.icons8.com/ios-filled/40/26e07f/ms-excel.png" /> &nbsp;&nbsp;<b>DOWNLOAD</b> </button>
    <br /> <br />
    <br />
    <input class="form-control" id="myInput" type="text" placeholder="Search..">

    <table class="table table-success table-striped">
        <thread>
            <tr>

                <th>
                    Complaint ID

                </th>
                <th>
                    Date
                </th>
                <th>
                    Subject
                </th>
                <th>
                    User Name
                </th>
                <th>
                    Status
                </th>

                <th>
                    Operations
                </th>


            </tr>
        </thread>
        @foreach (var item in Model)
        {
            <tbody id="myTable">
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Complaint_ID)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Date)
                    </td>

                    <td>
                        @Html.DisplayFor(modelItem => item.Subject)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.User_Name)
                    </td>
                    <td>
                        @if (item.Status == "Solved")
                        {
                                       <h4>
                                    <span class="badge bg-success">
                                    @Html.DisplayFor(modelItem => item.Status)
                                    </span>
                                    </h4>
                                    }
                                    else
                                    {
                    <h5>
                        <span class="badge  bg-warning text-dark">
                            @Html.DisplayFor(modelItem => item.Status)

                        </span>

                    </h5>

                                    }
                        </td>

                    <td>
                        <!--       <a href="@Url.Action("Details","Complaint", new { id = item.Complaint_ID })" class="btn btn-mini btn-info icon-edit bigger-10"><img src="https://img.icons8.com/ultraviolet/24/000000/ring-details.png" /></a> | -->
                        <a href="@Url.Action("Edit", "Complaint", new { id = item.Complaint_ID })" class="btn btn-mini btn-info icon-edit bigger-10"><img src="https://img.icons8.com/android/24/000000/edit.png" /></a>
                        <a href="@Url.Action("Admin_Details","Complaint", new { id = item.Complaint_ID })" class="btn btn-mini btn-info icon-edit bigger-10"><img src="https://img.icons8.com/ultraviolet/24/000000/ring-details.png" /></a>
                        <a href="@Url.Action("Admin_Delete","Complaint", new { id = item.Complaint_ID })" class="btn btn-mini btn-info icon-edit bigger-10" onclick="return confirm('Are you sure you to delete this Record?');"><img src="https://img.icons8.com/ios-filled/24/000000/delete-forever.png" /></a>

                    </td>
                </tr>
            </tbody>
        }

    </table>

    @Html.PagedListPager(Model, i => Url.Action("Admin_Index", "Complaint", new { i }))



    <link href="https://cdn.datatables.net/1.10.15/css/dataTables.bootstrap.min.css" rel="stylesheet" />
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />

    <script>

        function dellpopups() {
            Swal.fire({
                title: "Delete Successully !!",
                text: "",
                icon: "warning",
                dangerMode: true,
            })
        }

        $(document).ready(function () {
            $("#myInput").on("keyup", function () {
                var value = $(this).val().toLowerCase();
                $("#myTable tr").filter(function () {
                    $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                });
            });
        });
    </script>
</body>
</html>

FYP App/Views/Complaint/Create.cshtml
@model FYP_App.Models.Complaint_DB

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/UserLayOut.cshtml";
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
        * {
            box-sizing: border-box;
        }

        input[type=text], select, textarea {
            width: 100%;
            padding: 12px;
            border: 1px solid rgb(70, 68, 68);
            border-radius: 4px;
            resize: vertical;
        }

        input[type=email], select, textarea {
            width: 100%;
            padding: 12px;
            border: 1px solid rgb(70, 68, 68);
            border-radius: 4px;
            resize: vertical;
        }

        label {
            padding: 12px 12px 12px 0;
            display: inline-block;
        }

        input[type=submit] {
            background-color: rgb(37, 116, 161);
            color: white;
            padding: 12px 20px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            float: right;
        }

            input[type=submit]:hover {
                background-color: #45a049;
            }

        .container {
            border-radius: 5px;
            background-color: #f2f2f2;
            padding: 20px;
        }

        .col-25 {
            float: left;
            width: 25%;
            margin-top: 6px;
        }

        .col-75 {
            float: left;
            width: 75%;
            margin-top: 6px;
        }

        /* Clear floats after the columns */
        .row:after {
            content: "";
            display: table;
            clear: both;
        }

        /* Responsive layout - when the screen is less than 600px wide, make the two columns stack on top of each other instead of next to each other */
    </style>
</head>
<body>

    @using (Html.BeginForm())
    {<br />
        <br />
        <br />
        @Html.AntiForgeryToken()
        <div class="container">
            <h2 > ℂ𝕣𝕖𝕒𝕥𝕖 𝕐𝕠𝕦𝕣 ℂ𝕠𝕞𝕡𝕝𝕒𝕚𝕟𝕥</h2>
            <hr />

            <form>
                <div class="row">
                    <div class="col-25">
                        <label for="fname">User Name</label>
                    </div>
                    <div class="col-75">

                        @Html.TextBoxFor(model => model.User_Name, new { @class = "form-control", @Value = ViewBag.name, @readonly = "readonly" })
                        @Html.ValidationMessageFor(model => model.User_Name, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="row">
                    <div class="col-25">
                        <label for="lname">User Email</label>
                    </div>
                    <div class="col-75">
                        @Html.TextBoxFor(model => model.User_Email, new { @class = "form-control", @Value = ViewBag.email, @readonly = "readonly" })

                        @Html.ValidationMessageFor(model => model.User_Email, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.Date, new { @class = "form-control", @Value = ViewBag.date, @readonly = "readonly" })

                        @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="row">
                    <div class="col-25">
                        <label for="email">Complaint Subject </label>
                    </div>
                    <div class="col-75">
                        @Html.TextBoxFor(model => model.Subject, new { @class = "form-control", required = "required" })
                        @Html.ValidationMessageFor(model => model.Subject, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="row">
                    <div class="col-25">
                        <label for="feed_back">Complaint Description</label>
                    </div>
                    <div class="col-75">

                        @Html.TextAreaFor(model => model.Description, new { @style = "height:200px", placeholder = "Write something..", required = "required" })
                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="row">
                        <input type="submit" value="Submit">
                    </div>
                </div>

                <div>
                    <div class="row">
                        <a href="@Url.Action("Index","Complaint")" class="btn btn-mini btn-info icon-edit bigger-07"><img src="https://img.icons8.com/flat_round/30/000000/back--v1.png" />Back to List </a>

                    </div>
                </div>

            </form>
        </div>
    }
   
</body>
   
</html>


    

FYP App/Views/Complaint/Creates.cshtml
@model FYP_App.Models.Complaint_DB



<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
<script src="~/Scripts/jquery-1.9.1.js"></script>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div @*style="background-color:#E6E6FA"*@>
        <form>
            <div class="form-group">
                <label class=" font-weight-bold">User's Name</label>
                @Html.TextBoxFor(model => model.User_Name, new { @class = "form-control", @Value = ViewBag.name, @readonly = "readonly" })
            </div>
            <div class="form-group">
                <label class=" font-weight-bold">User's Email</label>
                @Html.TextBoxFor(model => model.User_Email, new { @class = "form-control", @Value = ViewBag.email, @readonly = "readonly" })
            </div>
            @Html.HiddenFor(model => model.Date, new { @class = "form-control", @Value = ViewBag.date, @readonly = "readonly" })

            <div class="form-group">
                <label class=" font-weight-bold">Subject</label>
                @Html.TextBoxFor(model => model.Subject, new { @class = "form-control" })
            </div>
            <div class="form-group">
                <label class=" font-weight-bold">Complaint Description </label>
                @Html.TextAreaFor(model => model.Description, new { cols = "125", rows = "5" })
            </div>


        </form>



        <p>
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Creates" class="btn btn-success" style="margin-bottom:10px" onclick="savedetails()" />
            </div>

        </p>
    </div>
}
    <script type="text/javascript">
        function savedetails() {
            var Complaint_ID = $("#Complaint_ID").val();
            var @ViewBag.name = $("#Name").val();
            var User_Email = $("#User_Email").val();
            var Subject = $("#Subject").val();
            var Description = $("#Description").val();

            var insertem = { "Complaint_ID": Complaint_ID, "Name": @ViewBag.name, "User_Email": User_Email, "Subject": Subject, "Description": Description };

            $.post('/Complaint/Creates', insertem,
                function (data) { if (data) { location = location.href; } }, 'json');

        }
        //$.ajax({

        //    type: "POST",
        //    url: "/UserVerify/Creates",
        //    data: myformdata,
        //    success: function () {
        //        $("#loaderDiv").hide();
        //        $("#myModal").modal("hide");

        //    }

        //})
    </script>

FYP App/Views/Complaint/Details.cshtml
@model FYP_App.Models.Complaint_DB

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/UserLayOut.cshtml";
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
        * {
            box-sizing: border-box;
        }

        input[type=text], select, textarea {
            width: 100%;
            padding: 12px;
            border: 1px solid rgb(70, 68, 68);
            border-radius: 4px;
            resize: vertical;
        }

        input[type=email], select, textarea {
            width: 100%;
            padding: 12px;
            border: 1px solid rgb(70, 68, 68);
            border-radius: 4px;
            resize: vertical;
        }

        label {
            padding: 12px 12px 12px 0;
            display: inline-block;
        }

        input[type=submit] {
            background-color: rgb(37, 116, 161);
            color: white;
            padding: 12px 20px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            float: right;
        }

            input[type=submit]:hover {
                background-color: #45a049;
            }

        .container {
            border-radius: 5px;
            background-color: #f2f2f2;
            padding: 20px;
        }

        .col-25 {
            float: left;
            width: 25%;
            margin-top: 6px;
        }

        .col-75 {
            float: left;
            width: 75%;
            margin-top: 6px;
        }

        /* Clear floats after the columns */
        .row:after {
            content: "";
            display: table;
            clear: both;
        }

        /* Responsive layout - when the screen is less than 600px wide, make the two columns stack on top of each other instead of next to each other */
    </style>
</head>
<body>
    <br />
    <br />
    <br />
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()


        <div class="container">
            <h2>
                ℂ𝕠𝕞𝕡𝕝𝕒𝕚𝕟𝕥 #    @Html.DisplayFor(model => model.Complaint_ID)
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

                𝕀𝕤𝕤𝕦𝕖 𝕕𝕒𝕥𝕖 :  @Html.DisplayFor(model => model.Date)
            </h2>
            <hr />
            <form>
                <div class="row">
                    <div class="col-25">
                        <label for="fname">User Name</label>
                    </div>
                    <div class="col-75">

                        @Html.TextBoxFor(model => model.User_Name, new { @class = "form-control", @readonly = "readonly" })
                    </div>
                </div>
                <div class="row">
                    <div class="col-25">
                        <label for="lname">User Email</label>
                    </div>
                    <div class="col-75">
                        @Html.TextBoxFor(model => model.User_Email, new { @class = "form-control", @readonly = "readonly" })



                    </div>
                </div>
                <div class="row">
                    <div class="col-25">
                        <label for="fname">Complaint Status</label>
                    </div>
                    <div class="col-75">

                        @Html.TextBoxFor(model => model.Status, new { @class = "form-control", @readonly = "readonly" })
                    </div>
                </div>
                <div class="row">
                    <div class="col-25">
                        <label for="email">Complaint Subject </label>
                    </div>
                    <div class="col-75">
                        @Html.TextBoxFor(model => model.Subject, new { @class = "form-control", @readonly = "readonly" })
                    </div>
                </div>

                <div class="row">
                    <div class="col-25">
                        <label for="feed_back">Complaint Description</label>
                    </div>
                    <div class="col-75">

                        @Html.TextAreaFor(model => model.Description, new { @style = "height:200px", @readonly = "readonly" })
                    </div>
                </div>


                <div>
                    <div class="row">
                        <a href="@Url.Action("Index","Complaint")" class="btn btn-mini btn-info icon-edit bigger-07"><img src="https://img.icons8.com/flat_round/30/000000/back--v1.png" />Back to List </a>

                    </div>
                </div>

            </form>
        </div>
    }
</body>

</html>